steps:
# Build the docker container (by running docker build)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/review:$BRANCH_NAME', '.']

# Add some tags so things look a little nicer in the console
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/review:$BRANCH_NAME', 'review-$BRANCH_NAME']
# Push it to the container store.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/review:$BRANCH_NAME']
  
# Deploy it to cloud run right away. 
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy', 
  '--region', 'us-central1', 
  '--image', 'gcr.io/$PROJECT_ID/review:$BRANCH_NAME', 
  '--labels', 'disposeable=true', # This is just an arbitrary label. But we will use it to tell some script to delete it after some time
  '--allow-unauthenticated', # If this isn't set, you can't access it from the outside world
  '--platform', 'managed', 
  'review-$BRANCH_NAME' # name the service
  ]
images:
- 'gcr.io/$PROJECT_ID/review:$BRANCH_NAME'